---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ggs-dataprep-script
  labels:
    app: ggs
data:
  install.sh: |
    #!/bin/bash

    # copy spds locally
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    rm -rf $GGS_DATA/*
    LOCAL_ZIP_DIR=$TMP/ggs-zip
    mkdir -p $LOCAL_ZIP_DIR
    parallel -a $SPD_LIST/spd.list aws s3 cp {1} $LOCAL_ZIP_DIR

    # create destination directory and extract datasets
    mkdir -p $GGS_DATA
    cd /usr/local/ggs/cli
    sh ./cli.sh extract  --s $LOCAL_ZIP_DIR --d $GGS_DATA

    # clean up
    rm -rf $LOCAL_ZIP_DIR