apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ggs-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: nginx_active_connections
      targetAverageValue: 12
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ggs
