---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ggs-data-pv
  labels:
    app: ggs
spec:
  capacity:
    storage: 100G
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: @PATH@
    server: @NFS_SERVER_DNS_NAME@
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ggs-data-pvc
  labels:
    app: ggs
spec:
  storageClassName: ""
  volumeName: ggs-data-pv
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100G